sudo: required
dist: trusty

env:
  global:
    # eratosthenes library management system url (encrypted)
    - secure: "ZYn4o229W7hq1uzj/Tii9h/a3iJlr9Li4TBaTNFXm6JY2H49lA57L1DIFUaTleTUx2Ibs2+kUrV3NFQ9Mo/ThO67gV5Q1XEMjxgFzAKt4AuWJ5TNbHxs3GBTjYc+129QCKSd0WdzrRDqEC2nZ9GjI+j7lS39DrjAMGg4wEp9b0U="
    # codebender compiler url (encrypted)
    - secure: "XRsqGDqdu5uhdj2lF4SZ6qv6Y0PdcRPcvE13XvVGnIYRZaITelP3eJNSvLPO+Q5k4mBmKCz8t+ws/OVRRwSAXYaKe0Z8ZXgEcNyo1nEwGekC35mTuG1FFfB/pbuBp5/OWjw6bgz2tEHhKuFIbHytpT9zJQYy+D07rzOYeUsZjOY="

before_script:
  - sudo chmod +x scripts/travis_install.sh
  - scripts/travis_install.sh
  - cd /opt/codebender/builder/Symfony
  - sudo chmod -R 777 app/cache app/logs
  - echo 'error_reporting =  E_ALL' >> /etc/php5/cli/conf.d/travis.ini
  - cd /opt/codebender/builder
  - sudo chmod +x scripts/travis_apache_install.sh
  - scripts/travis_apache_install.sh
  - cd /opt/codebender/builder/Symfony

script:
  - mkdir -p build/logs
  - bin/phpunit -c app/ --coverage-clover build/logs/clover.xml --stderr
  - bin/phpcpd --log-pmd build/pmd-cpd.xml --exclude app --exclude vendor --names-exclude *Test.php -n .
  - bin/phpmd src/Codebender/ xml cleancode,codesize,design,naming,unusedcode --exclude *Test.php --reportfile build/pmd.xml

after_script:
  - php composer.phar install --dev
  - php bin/coveralls -v

notifications:
  irc: "chat.freenode.net#codebender.cc"
