CodebenderApiBundle_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderApiBundle:Default:status }

CodebenderApiBundle_cb_website_compile:
    pattern:    /{auth_key}/{version}/website/compile
    defaults: { _controller: CodebenderApiBundle:Default:compileWebsite }

CodebenderApiBundle_compile:
    pattern:    /{auth_key}/{version}
    defaults: { _controller: CodebenderApiBundle:Default:compile }