CodebenderApiBundle_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderApiBundle:Default:status }

CodebenderApiBundle_compile:
    pattern:    /{auth_key}/{version}/compile
    defaults: { _controller: CodebenderApiBundle:Default:compile }
    requirements:
      _method: POST