parameters:
#    codebender_api.example.class: Codebender\ApiBundle\Example

services:
#    codebender_api.example:
#        class: %codebender_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    codebender_api.handler:
        class:        Codebender\ApiBundle\Handler\DefaultHandler